<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="CalculatorTest" tests="0" skipped="0" failures="0" errors="0" timestamp="1970-01-01T00:00:00" hostname="WKWIN4675635" time="0.0">
  <properties/>
  <system-out><![CDATA[
?[31mFailed scenarios:?[0m
?[31msrc/test/resources/calculator2.feature:6 ?[0m# Add two numbers -2 & 3
?[31msrc/test/resources/calculator2.feature:11 ?[0m# Add two numbers 10 & 1

4 Scenarios (?[31m2 failed?[0m, ?[32m2 passed?[0m)
12 Steps (?[31m2 failed?[0m, ?[36m1 skipped?[0m, ?[32m9 passed?[0m)
0m0.177s

java.lang.NullPointerException
	at stepdefs.CalculatorRunSteps.testAdd(CalculatorRunSteps.java:29)
	at ?.I add -2 and 3(src/test/resources/calculator2.feature:8)

java.lang.AssertionError: expected:<11> but was:<25>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at stepdefs.CalculatorRunSteps.validateResult(CalculatorRunSteps.java:34)
	at ?.the result should be 25(src/test/resources/calculator2.feature:14)

]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
